//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DAL.EFSource
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class HEEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“HEEntities”部分中的连接字符串初始化新 HEEntities 对象。
        /// </summary>
        public HEEntities() : base("name=HEEntities", "HEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HEEntities 对象。
        /// </summary>
        public HEEntities(string connectionString) : base(connectionString, "HEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HEEntities 对象。
        /// </summary>
        public HEEntities(EntityConnection connection) : base(connection, "HEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Catalogue> Catalogue
        {
            get
            {
                if ((_Catalogue == null))
                {
                    _Catalogue = base.CreateObjectSet<Catalogue>("Catalogue");
                }
                return _Catalogue;
            }
        }
        private ObjectSet<Catalogue> _Catalogue;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Product> Product
        {
            get
            {
                if ((_Product == null))
                {
                    _Product = base.CreateObjectSet<Product>("Product");
                }
                return _Product;
            }
        }
        private ObjectSet<Product> _Product;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RelationShip> RelationShip
        {
            get
            {
                if ((_RelationShip == null))
                {
                    _RelationShip = base.CreateObjectSet<RelationShip>("RelationShip");
                }
                return _RelationShip;
            }
        }
        private ObjectSet<RelationShip> _RelationShip;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Log_Operation> Log_Operation
        {
            get
            {
                if ((_Log_Operation == null))
                {
                    _Log_Operation = base.CreateObjectSet<Log_Operation>("Log_Operation");
                }
                return _Log_Operation;
            }
        }
        private ObjectSet<Log_Operation> _Log_Operation;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Catalogue EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCatalogue(Catalogue catalogue)
        {
            base.AddObject("Catalogue", catalogue);
        }
    
        /// <summary>
        /// 用于向 Product EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    
        /// <summary>
        /// 用于向 RelationShip EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRelationShip(RelationShip relationShip)
        {
            base.AddObject("RelationShip", relationShip);
        }
    
        /// <summary>
        /// 用于向 Log_Operation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToLog_Operation(Log_Operation log_Operation)
        {
            base.AddObject("Log_Operation", log_Operation);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HEModel", Name="Catalogue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Catalogue : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Catalogue 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Catalogue CreateCatalogue(global::System.String id)
        {
            Catalogue catalogue = new Catalogue();
            catalogue.Id = id;
            return catalogue;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pid
        {
            get
            {
                return _Pid;
            }
            set
            {
                OnPidChanging(value);
                ReportPropertyChanging("Pid");
                _Pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pid");
                OnPidChanged();
            }
        }
        private global::System.String _Pid;
        partial void OnPidChanging(global::System.String value);
        partial void OnPidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentPageIndex
        {
            get
            {
                return _CurrentPageIndex;
            }
            set
            {
                OnCurrentPageIndexChanging(value);
                ReportPropertyChanging("CurrentPageIndex");
                _CurrentPageIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentPageIndex");
                OnCurrentPageIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentPageIndex;
        partial void OnCurrentPageIndexChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentPageIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentPageStatus
        {
            get
            {
                return _CurrentPageStatus;
            }
            set
            {
                OnCurrentPageStatusChanging(value);
                ReportPropertyChanging("CurrentPageStatus");
                _CurrentPageStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentPageStatus");
                OnCurrentPageStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentPageStatus;
        partial void OnCurrentPageStatusChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentPageStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsFinished
        {
            get
            {
                return _IsFinished;
            }
            set
            {
                OnIsFinishedChanging(value);
                ReportPropertyChanging("IsFinished");
                _IsFinished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFinished");
                OnIsFinishedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsFinished;
        partial void OnIsFinishedChanging(Nullable<global::System.Int32> value);
        partial void OnIsFinishedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateTime
        {
            get
            {
                return _LastUpdateTime;
            }
            set
            {
                OnLastUpdateTimeChanging(value);
                ReportPropertyChanging("LastUpdateTime");
                _LastUpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateTime");
                OnLastUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HEModel", Name="Log_Operation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log_Operation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Log_Operation 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Log_Operation CreateLog_Operation(global::System.Int32 id)
        {
            Log_Operation log_Operation = new Log_Operation();
            log_Operation.Id = id;
            return log_Operation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpDes
        {
            get
            {
                return _OpDes;
            }
            set
            {
                OnOpDesChanging(value);
                ReportPropertyChanging("OpDes");
                _OpDes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpDes");
                OnOpDesChanged();
            }
        }
        private global::System.String _OpDes;
        partial void OnOpDesChanging(global::System.String value);
        partial void OnOpDesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OpTime
        {
            get
            {
                return _OpTime;
            }
            set
            {
                OnOpTimeChanging(value);
                ReportPropertyChanging("OpTime");
                _OpTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpTime");
                OnOpTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _OpTime;
        partial void OnOpTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnOpTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OpType
        {
            get
            {
                return _OpType;
            }
            set
            {
                OnOpTypeChanging(value);
                ReportPropertyChanging("OpType");
                _OpType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpType");
                OnOpTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _OpType;
        partial void OnOpTypeChanging(Nullable<global::System.Int32> value);
        partial void OnOpTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HEModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Product 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Product CreateProduct(global::System.String id)
        {
            Product product = new Product();
            product.Id = id;
            return product;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NickNames
        {
            get
            {
                return _NickNames;
            }
            set
            {
                OnNickNamesChanging(value);
                ReportPropertyChanging("NickNames");
                _NickNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NickNames");
                OnNickNamesChanged();
            }
        }
        private global::System.String _NickNames;
        partial void OnNickNamesChanging(global::System.String value);
        partial void OnNickNamesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CataId
        {
            get
            {
                return _CataId;
            }
            set
            {
                OnCataIdChanging(value);
                ReportPropertyChanging("CataId");
                _CataId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CataId");
                OnCataIdChanged();
            }
        }
        private global::System.String _CataId;
        partial void OnCataIdChanging(global::System.String value);
        partial void OnCataIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img
        {
            get
            {
                return _img;
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.String _img;
        partial void OnimgChanging(global::System.String value);
        partial void OnimgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GoodFor
        {
            get
            {
                return _GoodFor;
            }
            set
            {
                OnGoodForChanging(value);
                ReportPropertyChanging("GoodFor");
                _GoodFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GoodFor");
                OnGoodForChanged();
            }
        }
        private global::System.String _GoodFor;
        partial void OnGoodForChanging(global::System.String value);
        partial void OnGoodForChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoGoodFor
        {
            get
            {
                return _NoGoodFor;
            }
            set
            {
                OnNoGoodForChanging(value);
                ReportPropertyChanging("NoGoodFor");
                _NoGoodFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoGoodFor");
                OnNoGoodForChanged();
            }
        }
        private global::System.String _NoGoodFor;
        partial void OnNoGoodForChanging(global::System.String value);
        partial void OnNoGoodForChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsSetMap
        {
            get
            {
                return _IsSetMap;
            }
            set
            {
                OnIsSetMapChanging(value);
                ReportPropertyChanging("IsSetMap");
                _IsSetMap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSetMap");
                OnIsSetMapChanged();
            }
        }
        private Nullable<global::System.Int32> _IsSetMap;
        partial void OnIsSetMapChanging(Nullable<global::System.Int32> value);
        partial void OnIsSetMapChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> XiakeId
        {
            get
            {
                return _XiakeId;
            }
            set
            {
                OnXiakeIdChanging(value);
                ReportPropertyChanging("XiakeId");
                _XiakeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("XiakeId");
                OnXiakeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _XiakeId;
        partial void OnXiakeIdChanging(Nullable<global::System.Int32> value);
        partial void OnXiakeIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HEModel", Name="RelationShip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelationShip : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RelationShip 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static RelationShip CreateRelationShip(global::System.Int32 id)
        {
            RelationShip relationShip = new RelationShip();
            relationShip.Id = id;
            return relationShip;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PA
        {
            get
            {
                return _PA;
            }
            set
            {
                OnPAChanging(value);
                ReportPropertyChanging("PA");
                _PA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PA");
                OnPAChanged();
            }
        }
        private global::System.String _PA;
        partial void OnPAChanging(global::System.String value);
        partial void OnPAChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PB
        {
            get
            {
                return _PB;
            }
            set
            {
                OnPBChanging(value);
                ReportPropertyChanging("PB");
                _PB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PB");
                OnPBChanged();
            }
        }
        private global::System.String _PB;
        partial void OnPBChanging(global::System.String value);
        partial void OnPBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RType
        {
            get
            {
                return _RType;
            }
            set
            {
                OnRTypeChanging(value);
                ReportPropertyChanging("RType");
                _RType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RType");
                OnRTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _RType;
        partial void OnRTypeChanging(Nullable<global::System.Int32> value);
        partial void OnRTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Example
        {
            get
            {
                return _Example;
            }
            set
            {
                OnExampleChanging(value);
                ReportPropertyChanging("Example");
                _Example = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Example");
                OnExampleChanged();
            }
        }
        private global::System.String _Example;
        partial void OnExampleChanging(global::System.String value);
        partial void OnExampleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion
    
    }

    #endregion
    
}
